/**********************************************************************************************************************
 * \file auto_parking.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef MODULES_AUTO_PARKING_H_
#define MODULES_AUTO_PARKING_H_
#define IFX_CFG_USE_COMPILER_INTRINSICS   1   /* 컴파일러 built-in 사용 */
#define IFXCPU_INLINE                     1   /* iLLD 모든 API inline */
#include "sys_Init.h"
#include "ultrasonic.h"
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "IfxPort.h"
#include "IfxStm.h"

#include <stdint.h>
#include <stdbool.h>

#include "my_stdio.h"
#include "Motor.h"

#define START_THRESHOLD_CM  50.0f   // 주차 공간 60 cm
#define END_THRESHOLD_CM    25.0f   // 장애물과의 거리 16 cm
#define WIDTH_THRESHOLD_CM  30.0f

#define SEARCHING_SPEED     75.0f
#define PARKING_SPEED       75.0f
#define ROTATE_SPEED        150.0f

#define FRONT_DIR           1
#define BACK_DIR            0

#define WHEEL_CIRCUM        20.42f
#define ENC_DISK            20.0f
#define LENGTH_HALF_ENC     10

// 주차 공간 측정 상태
typedef enum {
    PARKING_STATE_SEARCHING,
    PARKING_STATE_MEASURING,
    PARKING_STATE_PARKING,
    PARKING_STATE_FINISH
} ParkingState;

extern volatile ParkingState parking_state;
extern volatile uint32_t count_enc;
// 주차 공간 폭 측정 관련 변수
extern uint64 space_measure_start_us;

void Parking_Init(void);
void calc_parking_distance(void);

void go_back(void);

extern volatile float right_distance;
extern volatile float left_distance;
extern volatile float rear_distance;

extern int VEL_flag;


#endif /* MODULES_AUTO_PARKING_H_ */
